language: python
services: sqlite
env:
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.5.1
python:
    - "3.3"
    - "2.7"
    - "2.6"
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r tests/test_requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source=reportview manage.py test
after_success: coveralls
matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.4.5