language: python
env:
    - DJANGO_VERSION=1.4.16
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.7.1
python:
    - 2.7
    - 2.6
install:
  - pip install -q django==$DJANGO_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install 'reportlab<3.0'; fi
  - pip install -r requirements.txt
  - pip install -r tests/test_requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source=reportview manage.py test
after_success: coveralls
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.6
      env: DJANGO_VERSION=1.7
    - python: 2.6
      env: DJANGO_VERSION=1.7.1
